library(dplyr)
activity <- read.table("./R_course/UCI HAR Dataset/activity_labels.txt",col.names = c("code","activity"))
features <- read.table("./R_course/UCI HAR Dataset/features.txt",col.names = c("n","functions"))
subject_test <- read.table("./R_course/UCI HAR Dataset/test/subject_test.txt",col.names = "subject")
x_test <- read.table("./R_course/UCI HAR Dataset/test/X_test.txt",col.names = features$functions)
y_test <- read.table("./R_course/UCI HAR Dataset/test/Y_test.txt",col.names = "code")
subject_train <- read.table("./R_course/UCI HAR Dataset/train/subject_train.txt",col.names = "subject")
x_train <- read.table("./R_course/UCI HAR Dataset/train/X_train.txt",col.names = features$functions)
y_train <- read.table("./R_course/UCI HAR Dataset/train/Y_train.txt",col.names = "code")
x <- rbind(x_test,x_train)
y <- rbind(y_test,y_train)
subject <- rbind(subject_test,subject_train)
merge_data <- cbind(subject,x,y)
tidy_data <- merge_data %>% select(subject,code,contains("mean"),contains("std"))
tidy_data$code <- activity[tidy_data$code,2]
names(tidy_data)[2] = "activity"
names(tidy_data)<-gsub("Acc", "Accelerometer", names(tidy_data))
names(tidy_data)<-gsub("Gyro", "Gyroscope", names(tidy_data))
names(tidy_data)<-gsub("BodyBody", "Body", names(tidy_data))
names(tidy_data)<-gsub("Mag", "Magnitude", names(tidy_data))
names(tidy_data)<-gsub("^t", "Time", names(tidy_data))
names(tidy_data)<-gsub("^f", "Frequency", names(tidy_data))
names(tidy_data)<-gsub("tBody", "TimeBody", names(tidy_data))
names(tidy_data)<-gsub("-mean()", "Mean", names(tidy_data), ignore.case = TRUE)
names(tidy_data)<-gsub("-std()", "STD", names(tidy_data), ignore.case = TRUE)
names(tidy_data)<-gsub("-freq()", "Frequency", names(tidy_data), ignore.case = TRUE)
names(tidy_data)<-gsub("angle", "Angle", names(tidy_data))
names(tidy_data)<-gsub("gravity", "Gravity", names(tidy_data))
names(tidy_data)
FinalData <- tidy_data %>%
  group_by(subject, activity) %>%
  summarise_all(funs(mean))
write.table(FinalData, "FinalData.txt", row.name=FALSE)
str(FinalData)
